# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish NPM package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

on:
  push:
    branches:
    - main
name: release-please
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: node
        package-name: nodebb-plugin-total-vote-count
    # The logic below handles the npm publication:
    - uses: actions/checkout@v3
      # these if statements ensure that a publication only occurs when
      # a new release is created:
      if: ${{ steps.release.outputs.release_created }}
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
        run_install: false
      if: ${{ steps.release.outputs.release_created }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm install
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      if: ${{ steps.release.outputs.release_created }}