on:
  push:
    branches:
    - main
name: release-please
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: node
        package-name: nodebb-plugin-ws-dice
        bootstrap-sha: 5736422f4eb86386ea5b154bc4fc99f1f2cff55c
    # The logic below handles the npm publication:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      # these if statements ensure that a publication only occurs when
      # a new release is created:
      if: ${{ steps.release.outputs.release_created }}
    - uses: pnpm/action-setup@v3.0.0
      with:
        version: 8
        run_install: false
      if: ${{ steps.release.outputs.release_created }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm install
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      if: ${{ steps.release.outputs.release_created }}
