on:
  push:
    branches:
    - main
name: release-please
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: googleapis/release-please-action@v5
      id: release
      with:
        release-type: node
        package-name: nodebb-plugin-ws-dice
        bootstrap-sha: 5736422f4eb86386ea5b154bc4fc99f1f2cff55c
    # The logic below handles the npm publication:
    - uses: actions/checkout@v6
      # these if statements ensure that a publication only occurs when
      # a new release is created:
      if: ${{ steps.release.outputs.release_created }}
    - uses: pnpm/action-setup@v6
      with:
        run_install: false
      if: ${{ steps.release.outputs.release_created }}
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
        package-manager-cache: false
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm install --frozen-lockfile
      if: ${{ steps.release.outputs.release_created }}
    - run: npm publish
      if: ${{ steps.release.outputs.release_created }}
